ra/view/artflow/css/config/routes.rb
Artflow::Application.routes.draw do

  devise_for :clients
  devise_for :designers
  devise_for :users

  resources :campaigns
  resources :clients
  resources :comments
  resources :creations do
    member do
      get 'permissions'
    end
  end
  resources :designers
  resources :plans
  resources :projects do
    resources :creations do
      resources :comments
    end
  end
  resources :project_assignments
  resources :subscriptions

  match '/vanity(/:action/:id)', :controller => :vanity, :as => :vanity
  
  get "pages/home"

  root :to => 'pages#home'
  

end

ra/view/artflow/css/app/views/layouts/_footer.html.erb
<% if mobile_request? %>
  <%= link_to_prefer_view :mobile %>
  |
  <%= link_to_prefer_view :standard %>
<% end %>

ra/view/artflow/css/app/views/layouts/_main_nav.html.erb
<% content_for :main_navigation do %>
  <nav id="main_nav" role="navigation">
    <ul>
      <%# START_HIGHLIGHT %>
      <%= nav_tab 'Home',        root_path,        current: current_tab %>
      <%= nav_tab 'Creations',   creations_path,   current: current_tab %>
      <%= nav_tab 'Campaigns',   campaigns_path,   current: current_tab %>
      <%= nav_tab 'Projects',    projects_path,    current: current_tab %>
      <%= nav_tab 'Designers',   designers_path,   current: current_tab %>
      <%# END_HIGHLIGHT %>
    </ul>
  </nav>
<% end %>

ra/view/artflow/css/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Artflow</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header id="page_header" role="banner">
    <nav id="utility">
      <p>
        You are logged in as <strong>Sam Spade</strong>
        <%= link_to "[Your Account]", "#" %> |
        <%= link_to "[Logout]", "#" %>
      </p>
    </nav>
    <%= link_to(
          image_tag("logo.png",
                    alt: "Artflow",
                    id: "logo"),
          root_url,
          title: "Dashboard") %>
   <%= yield :main_navigation %>
  </header>
  <%= image_tag("tagline.png",
                alt: "Creative File Management Made Easy",
                id: "tagline") %>
  <div class="container">
    <section id="content">
      <% if notice %>
        <p class="notification notice">
          <%= notice %>
        </p>
      <% end %>

      <% if alert %>
        <p class="notification alert">
          <%= alert %>
        </p>
      <% end %>

      <%= yield %>
    </section>
    <%# START:ipadsidebar %>
    <% if content_for?(:ipad_sidebar) %>
      <div id="ipad_sidebar">
        <%= yield :ipad_sidebar %>
      </div>
    <% end %>
    <%# END:ipadsidebar %>
    <section id="sidebar">
      <nav id="functional_nav">
        <ul>
          <% #if current_user.designer? %>
            <li><%= link_to 'Add Creation', new_creation_path %></li>
          <% #end %>
          <%= yield :functional_nav %>
        </ul>
      </nav>
      <%= yield :sidebar %>
      <section id="recent_activity">
        <header><h1 class="ir" id="recent">Recent Activity</h1></header>
        <%#= render partial: 'activity_items/recent' %>
      </section>
    </section>
  </div>
  <footer id="page_footer">
    <ul>
      <li><%= link_to "Contact", "" %></li>
      <li><%= link_to "Help", "" %></li>
      <li><%= link_to "File a Bug", "" %></li>
    </ul>
    <p>&copy; 2012 AwesomeCo. All Rights Reserved. All Wrongs Reversed.</p>
  </footer>
</body>
</html>

ra/view/artflow/css/app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>ArtFlow: Mobile Edition!</title>
    <%# START:content %>
    <%= javascript_include_tag 'jquery', 'jquery.mobile' %>
    <%= stylesheet_link_tag 'jquery.mobile-1.0b3/jquery.mobile-1.0b3' %>
    <%# START:end %>
  </head>
  <body>
    <%= yield %>
    <%# START_HIGHLIGHT %>
    <%= render partial: 'layouts/footer' %>
    <%# END_HIGHLIGHT %>
  </body>
</html>

ra/view/artflow/css/app/views/layouts/application.v1.mobile.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>ArtFlow: Mobile Edition!</title>
  </head>
  <body>
    <%= yield %>
    <%# START_HIGHLIGHT %>
    <%= render partial: 'layouts/footer' %>
    <%# END_HIGHLIGHT %>
  </body>
</html>

ra/view/artflow/css/app/views/layouts/application.v10.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Artflow</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header id="page_header" role="banner">
    <nav id="utility">
      <p>
        You are logged in as <strong>Sam Spade</strong>
        <%= link_to "[Your Account]", "#" %> |
        <%= link_to "[Logout]", "#" %>
      </p>
    </nav>
    <%= link_to(
          image_tag("logo.png",
                    alt: "Artflow",
                    id: "logo"),
          root_url,
          title: "Dashboard") %>
    <%# START_HIGHLIGHT %>
   <%= yield :main_navigation %>
    <%# END_HIGHLIGHT %>
  </header>
  <%= image_tag("tagline.png",
                alt: "Creative File Management Made Easy",
                id: "tagline") %>
  <div class="container">
    <section id="content">
      <%= yield %>
    </section>
    <section id="sidebar">
      <%= yield :sidebar %>
      <section id="recent_activity">
        <header><h1 class="ir" id="recent">Recent Activity</h1></header>
        <%= render partial: 'activity_items/recent' %>
      </section>
    </section>
  </div>
  <footer id="page_footer">
    <ul>
      <li><%= link_to "Contact", "" %></li>
      <li><%= link_to "Help", "" %></li>
      <li><%= link_to "File a Bug", "" %></li>
    </ul>
    <p>&copy; 2012 AwesomeCo. All Rights Reserved. All Wrongs Reversed.</p>
  </footer>
</body>
</html>

ra/view/artflow/css/app/views/layouts/application.v2.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Artflow</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

ra/view/artflow/css/app/views/layouts/application.v3.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Artflow</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header id="page_header">
  </header>

<%= yield %>

</body>
</html>

ra/view/artflow/css/app/views/layouts/application.v4.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Artflow</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header id="page_header" role="banner">
    <nav id="utility">
      <p>
        You are logged in as <strong>Sam Spade</strong>
        <%= link_to "[Your Account]", "#" %> |
        <%= link_to "[Logout]", "#" %>
      </p>
    </nav>
    <%= link_to(
          image_tag("logo.png",
                    alt: "Artflow",
                    id: "logo"),
          root_url,
          title: "Dashboard") %>
  </header>
  <%= image_tag("tagline.png",
                alt: "Creative File Management Made Easy",
                id: "tagline") %>
  <div class="container">

    <%= yield %>
  </div>
</body>
</html>

ra/view/artflow/css/app/views/layouts/application.v5.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Artflow</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header id="page_header" role="banner">
    <nav id="utility">
      <p>
        You are logged in as <strong>Sam Spade</strong>
        <%= link_to "[Your Account]", "#" %> |
        <%= link_to "[Logout]", "#" %>
      </p>
    </nav>
    <%= link_to(
          image_tag("logo.png",
                    alt: "Artflow",
                    id: "logo"),
          root_url,
          title: "Dashboard") %>
  </header>
  <%= image_tag("tagline.png",
                alt: "Creative File Management Made Easy",
                id: "tagline") %>
  <div class="container">

    <%= yield %>
  </div>
  <footer id="page_footer">
    <ul>
      <li><%= link_to "Contact", "" %></li>
      <li><%= link_to "Help", "" %></li>
      <li><%= link_to "File a Bug", "" %></li>
    </ul>
    <p>&copy; 2012 AwesomeCo. All Rights Reserved. All Wrongs Reversed.</p>
  </footer>
</body>
</html>

ra/view/artflow/css/app/views/layouts/application.v6.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Artflow</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header id="page_header" role="banner">
    <nav id="utility">
      <p>
        You are logged in as <strong>Sam Spade</strong>
        <%= link_to "[Your Account]", "#" %> |
        <%= link_to "[Logout]", "#" %>
      </p>
    </nav>
    <%= link_to(
          image_tag("logo.png",
                    alt: "Artflow",
                    id: "logo"),
          root_url,
          title: "Dashboard") %>
  </header>
  <%# START_HIGHLIGHT %>
  <%= image_tag("tagline.png",
                alt: "Creative File Management Made Easy",
                id: "tagline") %>
  <div class="container">
    <section id="content">
      <%= yield %>
    </section>
    <section id="sidebar">
    </section>
  </div>
  <%# END_HIGHLIGHT %>
  <footer id="page_footer">
    <ul>
      <li><%= link_to "Contact", "" %></li>
      <li><%= link_to "Help", "" %></li>
      <li><%= link_to "File a Bug", "" %></li>
    </ul>
    <p>&copy; 2012 AwesomeCo. All Rights Reserved. All Wrongs Reversed.</p>
  </footer>
</body>
</html>

ra/view/artflow/css/app/views/layouts/application.v7.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Artflow</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header id="page_header" role="banner">
    <nav id="utility">
      <p>
        You are logged in as <strong>Sam Spade</strong>
        <%= link_to "[Your Account]", "#" %> |
        <%= link_to "[Logout]", "#" %>
      </p>
    </nav>
    <%= link_to(
          image_tag("logo.png",
                    alt: "Artflow",
                    id: "logo"),
          root_url,
          title: "Dashboard") %>
  </header>
  <%# START:highlight %>
  <%= image_tag("tagline.png",
                alt: "Creative File Management Made Easy",
                id: "tagline") %>
  <div class="container">
    <section id="content">
      <%= yield %>
    </section>
    <section id="sidebar">
      <%# START_HIGHLIGHT %>
      <section id="recent_activity">
        <header><h1 class="ir" id="recent">Recent Activity</h1></header>
        <%= render partial: 'activity_items/recent' %>
      </section>
      <%# END_HIGHLIGHT %>
    </section>
  </div>
  <%# END:highlight %>
  <footer id="page_footer">
    <ul>
      <li><%= link_to "Contact", "" %></li>
      <li><%= link_to "Help", "" %></li>
      <li><%= link_to "File a Bug", "" %></li>
    </ul>
    <p>&copy; 2012 AwesomeCo. All Rights Reserved. All Wrongs Reversed.</p>
  </footer>
</body>
</html>

ra/view/artflow/css/app/views/layouts/application.v8.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Artflow</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header id="page_header" role="banner">
    <nav id="utility">
      <p>
        You are logged in as <strong>Sam Spade</strong>
        <%= link_to "[Your Account]", "#" %> |
        <%= link_to "[Logout]", "#" %>
      </p>
    </nav>
    <%= link_to(
          image_tag("logo.png",
                    alt: "Artflow",
                    id: "logo"),
          root_url,
          title: "Dashboard") %>
  </header>
  <%# START:highlight %>
  <%= image_tag("tagline.png",
                alt: "Creative File Management Made Easy",
                id: "tagline") %>
  <div class="container">
    <section id="content">
      <%= yield %>
    </section>
    <section id="sidebar">
      <%# START_HIGHLIGHT %>
      <%= yield :sidebar %>
      <%# END_HIGHLIGHT %>
      <section id="recent_activity">
        <header><h1 class="ir" id="recent">Recent Activity</h1></header>
        <%= render partial: 'activity_items/recent' %>
      </section>
    </section>
  </div>
  <%# END:highlight %>
  <footer id="page_footer">
    <ul>
      <li><%= link_to "Contact", "" %></li>
      <li><%= link_to "Help", "" %></li>
      <li><%= link_to "File a Bug", "" %></li>
    </ul>
    <p>&copy; 2012 AwesomeCo. All Rights Reserved. All Wrongs Reversed.</p>
  </footer>
</body>
</html>

ra/view/artflow/css/app/views/layouts/application.v9.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Artflow</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header id="page_header" role="banner">
    <nav id="utility">
      <p>
        You are logged in as <strong>Sam Spade</strong>
        <%= link_to "[Your Account]", "#" %> |
        <%= link_to "[Logout]", "#" %>
      </p>
    </nav>
    <%= link_to(
          image_tag("logo.png",
                    alt: "Artflow",
                    id: "logo"),
          root_url,
          title: "Dashboard") %>
    <%# START_HIGHLIGHT %>
    <nav id="main_nav" role="navigation">
      <ul>
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Creations', creations_path %></li>
        <li><%= link_to 'Campaigns', campaigns_path %></li>
        <li><%= link_to 'Projects', projects_path %></li>
      </ul>
    </nav>
    <%# END_HIGHLIGHT %>
  </header>
  <%= image_tag("tagline.png",
                alt: "Creative File Management Made Easy",
                id: "tagline") %>
  <div class="container">
    <section id="content">
      <%= yield %>
    </section>
    <section id="sidebar">
      <%= yield :sidebar %>
      <section id="recent_activity">
        <header><h1 class="ir" id="recent">Recent Activity</h1></header>
        <%= render partial: 'activity_items/recent' %>
      </section>
    </section>
  </div>
  <footer id="page_footer">
    <ul>
      <li><%= link_to "Contact", "" %></li>
      <li><%= link_to "Help", "" %></li>
      <li><%= link_to "File a Bug", "" %></li>
    </ul>
    <p>&copy; 2012 AwesomeCo. All Rights Reserved. All Wrongs Reversed.</p>
  </footer>
</body>
</html>