ra/v3/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :recipes

  root 'recipes#index'

end

ra/v3/app/models/direction.rb
class Direction < ActiveRecord::Base
  belongs_to :recipe
end

ra/v3/app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe
end

ra/v3/app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :ingredients
  has_many :directions
  belongs_to :user

  accepts_nested_attributes_for :ingredients,
                                reject_if: proc {|attrs| attrs['name'].blank?},
                                allow_destroy: true

  accepts_nested_attributes_for :directions,
                                reject_if: proc {|attrs| attrs['step'].blank?},
                                allow_destroy: true

  validates :title, :description, :image, presence: true

  has_attached_file :image, :styles => { :medium => "400x400>"}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

ra/v3/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

ra/v3/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all.order('created_at DESC')
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = current_user.recipes.build
  end

  def create
    @recipe = current_user.recipes.build(recipe_params())
    if @recipe.save
      redirect_to @recipe, notice: "Successfully created new!"
    else
      render 'new'
    end
  end

  def edit
    @recipe = current_user.recipes.find(params[:id])
  end

  def update
    @recipe = current_user.recipes.find(params[:id])
    if @recipe.update(recipe_params())
      redirect_to @recipe
    else
      render 'edit'
    end
  end

  def destroy
    @recipe = current_user.recipes.find(params[:id])
    @recipe.destroy
    redirect_to root_path, notice: "Successfully update"
  end


  private

  def recipe_params
    params.require(:recipe).permit(:title, :description, :image,
                                   ingredients_attributes: [:id, :name, :_destroy],
                                   directions_attributes: [:id, :step, :_destroy])
  end

end

ra/v3/app/helpers/recipes_helper.rb
module RecipesHelper
end

ra/v3/app/views/recipes/_direction_fields.html.haml
.form-inline.clearfix
  .nested-fields
    = f.input :step, input_html: {class: 'form-input form-control'}
    = link_to_remove_association 'Remove', f, class: 'btn btn-default form-button'

ra/v3/app/views/recipes/_form.html.haml
= simple_form_for(@recipe, html:{multipart: true}) do |f|
  - if @recipe.errors.any?
    %p
      = @recipe.errors.count
      Prevented this recipe froms saving
    %ul
      - @recipe.errors.full_messages.each do |msg|
        %li= msg

  .panel-body
    = f.input :title, input_html: {class: 'form-control'}
    = f.input :description, input_html: {class: 'form-control'}
    = f.input :image, input_html: {class: 'form-control'}

    .row
      .col-md-6
        %h3 Ingredients
        #ingredients
          = f.simple_fields_for :ingredients do |ingredient|
            = render 'ingredient_fields', f: ingredient
          .links
            = link_to_add_association 'Add Ingredient', f, :ingredients, class: 'btn btn-default add-button'

      .col-md-6
        %h3 Directions
        #directions
          = f.simple_fields_for :directions do |direction|
            = render 'direction_fields', f: direction
          .links
            = link_to_add_association 'Add Direction', f, :directions, class: 'btn btn-default add-button'

  = f.button :submit, class: "btn btn-default"

ra/v3/app/views/recipes/_ingredient_fields.html.haml
.form-inline.clearfix
  .nested-fields
    = f.input :name, input_html: {class: 'form-input form-control'}
    = link_to_remove_association 'Remove', f, class: 'btn btn-default form-button'

ra/v3/app/views/recipes/edit.html.haml
%h1 Edit Recipe
= render 'form'

= link_to "Back", root_path, class: 'btn btn-default'

ra/v3/app/views/recipes/index.html.haml
- @recipes.each_slice(3) do |rs|
  .row
    - rs.each do |recipe|
      .col-md-4
        .recipe
          .image_wrapper
            = link_to recipe do
              = image_tag recipe.image.url(:medium, class:"img-responsive")
          %h2= link_to recipe.title, recipe

ra/v3/app/views/recipes/new.html.haml
%h1 New Recipe

= render 'form'

%br/

= link_to 'Back', root_path, class: "btn btn-default"

ra/v3/app/views/recipes/show.html.haml
.main_content
  #recipe_top.row
    .col-md-4
      = image_tag @recipe.image.url(:medium, class: 'recipe_image img-responsive')
    .col-md-8
      #recipe_info
        %h1= @recipe.title
        %p= @recipe.description
        %p 
          Subemitted by
          = @recipe.user.email

  .row
    .col-md-6
      -if not @recipe.ingredients.empty?
        #ingredients
          %h2 Ingredients
          %ul
            - @recipe.ingredients.each do |ingredient|
              %li= ingredient.name

    .col-md-6
      -if not @recipe.directions.empty?
        #directions
          %h2 Directions
          %ul
            - @recipe.directions.each do |direction|
              %li= direction.step

  .row
    .col-md-12
      = link_to "Back", root_path, class: "btn btn-default"
      = link_to 'Edit', edit_recipe_path, class: 'btn btn-default'
      = link_to 'Delete', recipe_path, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-default'